name: ci

on: push

jobs:
  ci:
    env:
      MIX_ENV: test
      BRAINTREE_MERCHANT_ID: ${{ secrets.BRAINTREE_MERCHANT_ID }}
      BRAINTREE_PUBLIC_KEY: ${{ secrets.BRAINTREE_PUBLIC_KEY }}
      BRAINTREE_PRIVATE_KEY: ${{ secrets.BRAINTREE_PRIVATE_KEY }}
      BRAINTREE_MASTER_MERCHANT_ID: ${{ secrets.BRAINTREE_MASTER_MERCHANT_ID }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: '1.10'
              otp: '21.3'
            exclude_tags: 'integration'
          - pair:
              elixir: '1.12'
              otp: '24.0'
            lint: lint
            exclude_tags: 'nothing'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-

      - name: Run mix deps.get
        run: mix deps.get --only test

      - name: Run mix format
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Run mix deps.unlock
        run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - name: Run mix deps.compile
        run: mix deps.compile

      - name: Run mix compile
        run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Run credo
        run: mix credo --strict
        if: ${{ matrix.lint }}

      - name: Run mix test
        run: mix test --exclude ${{ matrix.exclude_tags }}

      - name: Run dialyzer
        run: mix dialyzer
        if: ${{ matrix.lint }}
